model_params:
  name: BetaVAE_new
  beta_weight: 0.02
  learning_rate: 0.0005
  model_architecture_name: VAE_Linear_2605

DataModule_params:
  data_path: /data1/dose-3d-generative/data/training-data/PHSPs_without_VR/Filtered_E5.6_s0.0.npy
  batch_size: 10000
  num_workers: 0
  test_fraction: 0.0
  validation_fraction: 0.4
  shuffle_train: true
  random_seed: 123
  columns_keys:
  - E
  - X
  - Y
  - dX
  - dY
  - dZ
  
checkpoint_params:
  # dirpath: /home/jakmic/Projekty/dose3d-phsp/AE_VAE/Lighting_Autoencoders/checkpoints/BetaVAE/
  filename: checkpoint_BetaVAE_date2805_{epoch}epoch
  auto_insert_metric_name: false
  save_last: true
  save_top_k: -1
  every_n_epochs: 1

trainer_params:
  max_epochs: 6
  log_every_n_steps: 1

CSVLogger_params:
  save_dir: "/home/jakmic/Projekty/dose3d-phsp/AE_VAE/Lightning_Autoencoders/results/"
  name: 'BetaVAE'
  # version: null