model_params:
    name: GAN
    latent_dim: 6
    learning_rate: 0.0005
    b1: 0.5
    b2: 0.999
    weight_decay: 0.0
    scheduler_gamma: 1.0
    # model_architecture_name: VAE_Linear_2605

general_params:
    manual_seed: 1234

DataModule_params:
    data_path: / data1/dose-3d-generative/data/training-data/PHSPs_without_VR/Filtered_E5.6_s0.0.npy
    batch_size: 10000
    num_workers: 0
    test_fraction: 0.0
    validation_fraction: 0.4
    shuffle_train: true
    random_seed: 123
    columns_keys:
    - E
    - X
    - Y
    - dX
    - dY
    - dZ

checkpoint_params:
    # dirpath: /home/jakmic/Projekty/dose3d-phsp/AE_VAE/Lighting_Autoencoders/checkpoints/BetaVAE/
    filename: checkpoint_GAN_2706_{epoch}epoch
    auto_insert_metric_name: false
    save_last: true
    save_top_k: -1
    every_n_epochs: 5

trainer_params:
    max_epochs: 50
    log_every_n_steps: 1

CSVLogger_params:
    save_dir: "/home/jakmic/Projekty/dose3d-phsp/GAN/Lightning_GANs/results/"
    name: 'GAN'
    # version: null
